import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge

@cocotb.test()
async def test_mac_tx_full_frame(dut):
    """Test full MAC TX pipeline including Preamble, Data, and CRC-32."""
    
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())

    await FallingEdge(dut.clk)
    dut.rst_n.value = 0
    dut.s_axis_tvalid.value = 0
    dut.s_axis_tlast.value = 0
    dut.s_axis_tdata.value = 0
    dut.m_axis_tready.value = 1 
    await FallingEdge(dut.clk)
    dut.rst_n.value = 1

    dut._log.info("--- WAKING UP THE NETWORK ---")
    
    dut.s_axis_tvalid.value = 1
    dut.s_axis_tdata.value = 0xAA 
    await FallingEdge(dut.clk)

    # Check Preamble
    for _ in range(7):
        assert dut.m_axis_tdata.value == 0x55
        await FallingEdge(dut.clk)

    # Check SFD
    assert dut.m_axis_tdata.value == 0xD5
    await FallingEdge(dut.clk)

    # Check Data
    dut._log.info("--- TRANSMITTING PAYLOAD ---")
    dut.s_axis_tlast.value = 1 # End packet on the very first byte
    await FallingEdge(dut.clk)
    
    # Host is done
    dut.s_axis_tvalid.value = 0
    dut.s_axis_tlast.value = 0

    dut._log.info("--- STAMPING THE WAX SEAL (CRC-32) ---")
    
    # Read the 4 CRC bytes generated by the hardware
    crc_bytes = []
    for i in range(4):
        crc_bytes.append(hex(dut.m_axis_tdata.value))
        dut._log.info(f"FCS Byte {i+1}: {hex(dut.m_axis_tdata.value)}")
        await FallingEdge(dut.clk)
        
    dut._log.info(f"Final Hardware Hash: {crc_bytes}")
    dut._log.info("🟢 LEVEL 2 COMPLETE! Full Ethernet Frame Generated.")
